
11-15-2018
* /var/www/html/phpinfo.php  created.
 shows pdo_sqlite enabled
* php version 5.5.23  possible problem

* /etc/php.ini
[sqlite]
; http://php.net/sqlite.assoc-case
;sqlite.assoc_case = 0

[sqlite3]
;sqlite3.extension_dir =
* /var/www/html/cologne/mw/web/webtc/getwordviewmodel.php
add require_once('dbgprint.php');
Add dbgprint(true statements
* change permissions on mw to 0777  
so can debug with dbgprint.php
it was rwxr-xr-x
chmod -R 0777 webtc
* /var/www/html/cologne/mw/web/webtc/dal.php
[root@sanskrit1 webtc]# php dal.php
PHP Warning:  Module 'PDO' already loaded in Unknown on line 0
PHP Parse error:  syntax error, unexpected '[' in /var/www/html/cologne/mw/web/webtc/dal.php on line 212
  $item00 = item0[0];
This is indeed an error. no '$'
Occurs 7 times.  $item00 only used in a dbgprint statement.
Under php 7.1.9, this does not break 
 Changed to
 $item00 = $item0[0];
* download websanlexicon repository
download_websanlexicon.sh
# from https://github.com/funderburkjim/websanlexicon
curl --header "Host: codeload.github.com" --header "User-Agent: Mozilla/5.0 (Win
dows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" --header "Accept-Language: en-US,en;q=0.9,hi;q=0.8,ms;q=0.7,de;q=0.6" --header "Cookie: _octo=GH1.1.1954090048.1500347832; _ga=GA1.2.1727540290.1492572837; logged_in=yes; dotcom_user=funderburkjim; _gat=1" --header "Connection: keep-alive" "https://codeload.github.com/funderburkjim/websanlexicon/zip/master" -o "websanlexicon-master.zip" -L
* unzip and rename websanlexicon
unzip websanlexicon-master.zip
mv websanlexicon-master websanlexicon
# no need for the zip file
rm websanlexicon-master.zip
[ answer 'y' at prompt: rm: remove regular file `websanlexicon-master.zip'?]
* note on python version (preparatory for next step
[root@sanskrit1 v00]# python --version
Python 2.7.13 :: Anaconda 2.1.0 (64-bit)
[root@sanskrit1 v00]# which python
/root/anaconda/bin/python
[
* install python module 'mako' so next step will work
conda install mako
Several other packages updated:
** log of conda install
[root@sanskrit1 v00]# conda install mako
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /root/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    asn1crypto-0.22.0          |           py27_0         145 KB
    certifi-2016.2.28          |           py27_0         211 KB
    cffi-1.10.0                |           py27_0         329 KB
    conda-4.3.30               |   py27h6ae6dc7_0         507 KB
    conda-env-2.6.0            |                0          502 B
    cryptography-1.8.1         |           py27_0         850 KB
    enum34-1.1.6               |           py27_0          53 KB
    idna-2.6                   |           py27_0         122 KB
    ipaddress-1.0.18           |           py27_0          31 KB
    libffi-3.2.1               |                1          38 KB
    mako-1.0.6                 |           py27_0         108 KB
    markupsafe-1.0             |           py27_0          31 KB
    openssl-1.0.2l             |                0         3.2 MB
    packaging-16.8             |           py27_0          30 KB
    pycosat-0.6.2              |           py27_0         194 KB
    pycparser-2.18             |           py27_0         165 KB
    pyopenssl-17.0.0           |           py27_0          74 KB
    pyparsing-2.2.0            |           py27_0          94 KB
    python-2.7.13              |                0        11.5 MB
    requests-2.14.2            |           py27_0         700 KB
    ruamel_yaml-0.11.14        |           py27_1         361 KB
    setuptools-36.4.0          |           py27_1         557 KB
    six-1.10.0                 |           py27_0          16 KB
    sqlite-3.13.0              |                0         4.0 MB
    tk-8.5.18                  |                0         1.9 MB
    yaml-0.1.6                 |                0         246 KB
    zlib-1.2.11                |                0         109 KB
    ------------------------------------------------------------
                                           Total:        25.4 MB

The following NEW packages will be INSTALLED:

    asn1crypto:   0.22.0-py27_0
    certifi:      2016.2.28-py27_0
    conda-env:    2.6.0-0
    enum34:       1.1.6-py27_0
    idna:         2.6-py27_0
    ipaddress:    1.0.18-py27_0
    mako:         1.0.6-py27_0
    packaging:    16.8-py27_0
    ruamel_yaml:  0.11.14-py27_1

The following packages will be UPDATED:

    cffi:         0.8.6-py27_0 --> 1.10.0-py27_0
    conda:        3.7.0-py27_0 --> 4.3.30-py27h6ae6dc7_0
    cryptography: 0.5.4-py27_0 --> 1.8.1-py27_0
    libffi:       3.0.13-0     --> 3.2.1-1
    markupsafe:   0.23-py27_0  --> 1.0-py27_0
    openssl:      1.0.1h-1     --> 1.0.2l-0
    pycosat:      0.6.1-py27_0 --> 0.6.2-py27_0
    pycparser:    2.10-py27_0  --> 2.18-py27_0
    pyopenssl:    0.14-py27_0  --> 17.0.0-py27_0
    pyparsing:    2.0.1-py27_0 --> 2.2.0-py27_0
    python:       2.7.8-1      --> 2.7.13-0
    requests:     2.4.1-py27_0 --> 2.14.2-py27_0
    setuptools:   5.8-py27_0   --> 36.4.0-py27_1
    six:          1.8.0-py27_0 --> 1.10.0-py27_0
    sqlite:       3.8.4.1-0    --> 3.13.0-0
    tk:           8.5.15-0     --> 8.5.18-0
    yaml:         0.1.4-0      --> 0.1.6-0
    zlib:         1.2.7-0      --> 1.2.11-0

Proceed ([y]/n)? y

Fetching packages ...
asn1crypto-0.2 100% |################################| Time: 0:00:00  27.19 MB/s
certifi-2016.2 100% |################################| Time: 0:00:00   7.34 MB/s
cffi-1.10.0-py 100% |################################| Time: 0:00:00   8.12 MB/s
conda-4.3.30-p 100% |################################| Time: 0:00:00   4.52 MB/s
conda-env-2.6. 100% |################################| Time: 0:00:00 802.11 kB/s
cryptography-1 100% |################################| Time: 0:00:00   5.10 MB/s
enum34-1.1.6-p 100% |################################| Time: 0:00:00  25.73 MB/s
idna-2.6-py27_ 100% |################################| Time: 0:00:00  31.68 MB/s
ipaddress-1.0. 100% |################################| Time: 0:00:00  23.78 MB/s
libffi-3.2.1-1 100% |################################| Time: 0:00:00  24.85 MB/s
mako-1.0.6-py2 100% |################################| Time: 0:00:00  30.71 MB/s
markupsafe-1.0 100% |################################| Time: 0:00:00  24.64 MB/s
openssl-1.0.2l 100% |################################| Time: 0:00:00  13.08 MB/s
packaging-16.8 100% |################################| Time: 0:00:00  16.95 MB/s
pycosat-0.6.2- 100% |################################| Time: 0:00:00  27.95 MB/s
pycparser-2.18 100% |################################| Time: 0:00:00  30.05 MB/s
pyopenssl-17.0 100% |################################| Time: 0:00:00  27.90 MB/s
pyparsing-2.2. 100% |################################| Time: 0:00:00  32.67 MB/s
python-2.7.13- 100% |################################| Time: 0:00:01   8.36 MB/s
requests-2.14. 100% |################################| Time: 0:00:00   5.32 MB/s
ruamel_yaml-0. 100% |################################| Time: 0:00:00   7.79 MB/s
setuptools-36. 100% |################################| Time: 0:00:00  13.72 MB/s
six-1.10.0-py2 100% |################################| Time: 0:00:00  15.59 MB/s
sqlite-3.13.0- 100% |################################| Time: 0:00:00   4.53 MB/s
tk-8.5.18-0.ta 100% |################################| Time: 0:00:00   3.48 MB/s
yaml-0.1.6-0.t 100% |################################| Time: 0:00:00  19.36 MB/s
zlib-1.2.11-0. 100% |################################| Time: 0:00:00  30.55 MB/s
Extracting packages ...
[      COMPLETE      ] |##################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |##################################################| 100%
Linking packages ...
[      COMPLETE      ] |##################################################| 100%

* reinstall websanlexicon code
The above error was corrected in websanlexicon template for dal.php.
The following script installs new web code for all the dictionaries.
cd websanlexicon/v00
sh redo_web_all.sh
* note on links to cologne that remain
There are a few links still to cologne:
 Such as Whitney links.
These currently lead to an error, since sanskritlibrary.org is 'https://'
and colonge is not.
Soon Cologne will be https also;these problems should go away then.
* apidev dal.php and dalraw.php  -- same change
* TODO  https://sanskritlibrary.org/integratedDictionaries.html
  This now works for MW and Wilson, but not bohtlingk.
  Probably need to change links to be like mw and wilson.
