These notes pertain to various things tried in Github in
the testing repository.
Begun Jan 31, 2014.
This file best viewed in emacs org mode.
I am using the windows Github gui client.

* create testing repository
 Used github 'create new repository' function
   This generated a local folder named 'testing' under Documents/GitHub
   Folder contained three files
   .git folder
   .gitattributes file
   .gitignore file

* created this notes.org file
Opened the testing repository in 'Explorer'.
Created this file via 'New...' 
Began editing in Emacs.
Saved file, removed notes.org~ 
In GitHub client, wrote an informational message for notes.org,
pressed commit.  At this point, nothing happened at the server level - this
change still local.
Then pressed 'Publish', and the notes.org, and several other things, were
published on server.
* Create subfolder:
In Explorer, created 'subtest' folder.
This empty folder was not visible in GitHub client.
Created subtest/subtest.txt and wrote small message therein.
Then, was shown an 'uncommitted change'. Committed it, then 'synced'.
Now, on server, there is shown a 'subtest' folder, which contains subtest.txt,
as intended.

* Modify notes.org on server.
Let's see how this shows up locally.

